name: Half-year calendar
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - uses: lowlight/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.SECRET }}
          base: ""
          plugin_isocalendar: yes
